# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include [override.d, override.yaml]

logging: !include logging.yaml

kvmd:
    auth: !include auth.yaml

    info:
        fan:
            unix: /run/kvmd/fan.sock

    hid:
        type: otg

    atx:
        type: disabled

    msd:
        type: otg

    streamer:
        h264_bitrate:
            default: 5000
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/video0"
            # - "-s 0.0.0.0"
            - "-r 1920x1080"
            - "--venc-format=1"
            - "--tcp-nodelay"
            - "--vi-buffer-num=3"
            - "--vi-format=19"
            # - "--persistent"
            # - "--dv-timings"
            # - "--desired-fps={desired_fps}"
            # - "--unix={unix}"
            # - "--unix-rm"
            # - "--unix-mode=0660"
            # - "--exit-on-parent-death"
            # - "--process-name-prefix={process_name_prefix}"
            # - "--notify-parent"
            # - "--no-log-colors"
            # - "--jpeg-sink=kvmd::ustreamer::jpeg"
            # - "--jpeg-sink-mode=0660"
            # - "--h264-sink=kvmd::ustreamer::h264"
            # - "--h264-sink-mode=0660"
            # - "--h264-bitrate={h264_bitrate}"
            # - "--h264-gop={h264_gop}"

    gpio:
        scheme:
            __v3_usb_breaker__:
                pin: 5
                mode: output
                initial: true
                pulse: false


vnc:
    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"